/* ============================================================
   Project content
   One object per project. Add / edit / reorder projects here —
   everything else on the site is generated from this array.
   Set `hidden: true` to keep a project out of the public index
   while still allowing it to be deep-linked if you ever need to.
   ============================================================ */
window.PROJECTS = [
  {
    id: "b2b",
    num: "01",
    name: "Current Work",
    accent: "var(--a-data)",
    glyph: "B",
    category: "Product Design · User Flows · Prototyping · Energy Sector",
    year: "2023 – today",
    role: "UX/UI Designer & Digital Product Designer",
    duration: "ongoing",
    team: "Small development team · Platform & products",
    skills: ["User Flows", "User Journeys", "Prototyping", "Requirements Clarification", "Information Architecture", "Design System"],
    collab: ["CTO and project management", "Development", "Energy sector specialists"],
    contribution: ["Prototyping to clarify and discuss requirements", "Translating domain requirements and technical constraints into concrete UX/UI approaches", "Designing and visualising user flows", "Building information architectures for different roles and permission levels", "Developing and reusing consistent UI components and design system principles"],
    tags: ["Energy Sector", "Product Design", "User Flows", "Prototyping"],
    confidential: true,
    cta: "More about how I work",
    sub: "I work in a small development team alongside energy sector specialists. Together we build a B2B digital platform and several products on top of it.",
    teaser: "Complex energy processes — designed to be understood.",
    ndaNote: "For confidentiality reasons I cannot publish product views or project-specific details. I am happy to talk about my role and way of working in more depth in person.",
    contextTitle: "Starting point",
    context: "A B2B digital platform in the energy sector and several products built on top of it — for business customers, plant owners, installers, partners and internal departments.",
    context2: "The products help to",
    contextList: ["simplify energy processes", "make consumption and generation more transparent", "make opportunities around energy assets accessible"],
    challenge: "A domain dense with expertise, many dependencies, and requirements that are often not yet articulated when a project starts.",
    challengeTitle: "Learning field",
    challengeList: ["Working with development and energy sector specialists", "Diving into complex topics, processes and dependencies", "Bringing requirements, technical possibilities and design together", "Continuous evolution of the platform and its products", "Direct exchange within a young, open company", "Current developments around AI and what they mean for digital products and processes"],
    challenge2: "Plus the question of how the same platform stays understandable for very different roles without building a separate product for every group.",
    approach: "I translate user needs, domain requirements and technical constraints into concrete UX/UI approaches: prototypes to resolve open questions, visualised user flows, and information architectures for different roles and permission levels.",
    approach2: "I work closely with the CTO, project management, development and the specialist departments, and keep evolving consistent UI components and design system principles so that solutions stay reusable.",
    cover: null,
    gallery: [],
  },
  {
    id: "zeiga",
    num: "02",
    name: "Zeigä",
    accent: "var(--a-zeiga)",
    glyph: "Z",
    category: "Digital Inclusion · App",
    year: "2023",
    role: "Interaction Design · Research",
    duration: "14 weeks",
    team: "Bachelor project · 2 people, Silvan Weber",
    skills: ["Interaction Design", "Accessibility", "Usability"],
    tags: ["Interaction Design", "Accessibility", "Bachelor Project"],
    sub: "A digital concept that supports older people in using their smartphone independently. Developed together with a fellow student.",
    teaser: "More independence and confidence in a digitalised society.",
    contextTitle: "Starting point",
    context: "A bachelor project for two: a digital concept supporting older people in using their smartphone independently — over 14 weeks, with access to seniors.",
    context2: "Smartphones have become inseparable from everyday life, yet for many older people they remain a barrier.",
    challenge: "Uncertainty, the fear of «breaking something» and a lack of patience in their surroundings lead to digital exclusion.",
    challenge2: "Help has to support without patronising — and work on the device itself, not in a separate course.",
    approach: "In interviews with seniors we mapped the biggest points of friction. From that came an interaction model that breaks tasks into the smallest comprehensible steps and makes progress visible.",
    approach2: "Large tap targets, high contrast and a calm, encouraging tone form the foundation. In usability testing the flow was tried out right at the kitchen table.",
    learnings: ["Tone is interface: language decides whether people trust it", "Tests in real settings surface problems that stay invisible in the lab", "Step-by-step guidance needs a way back at every point", "Small steps and clear feedback take away the fear of mistakes"],
    cover: { type: "image", src: "assets/zeiga-illustration.jpg", fit: "contain", bg: "paper" },
    gallery: [
      { type: "image", src: "assets/zeiga-testing.jpg", fit: "cover", label: "Usability test at the kitchen table", span: "wide" },
      { type: "video", src: "assets/zeiga-app.mp4", fit: "contain", label: "App demo", span: "wide" },
    ],
  },
  {
    id: "repose",
    num: "03",
    name: "Repose",
    accent: "var(--a-repose)",
    glyph: "R",
    category: "Service Design · Health",
    year: "2024",
    role: "Service Design · Interaction Design",
    duration: "16 weeks",
    team: "3 people",
    skills: ["Service Design", "Research", "Interaction Design"],
    tags: ["Student Project", "Service Design", "Research", "Interaction Design"],
    sub: "A service concept for a life as self-determined as possible for people with dementia in their familiar surroundings.",
    teaser: "Safety and dignity at home — for as long as possible.",
    contextTitle: "Starting point",
    context: "A service concept built by three people over 16 weeks: a life as self-determined as possible for people with dementia in their familiar surroundings — thought through together with those affected and their families.",
    context2: "A dementia diagnosis often means an early loss of independence. Relatives worry, those affected feel stripped of agency.",
    challenge: "Safety quickly turns into surveillance. The balancing act: enough of a safety net for relatives without limiting the dignity and autonomy of those affected.",
    challenge2: "And with it the question of which sensor data is actually needed, and when a system is allowed to intervene.",
    approach: "A wristband bundles sensors — ECG, gyro, voice, location — into gentle signals. Situations are inferred from the data without constant monitoring.",
    approach2: "In detailed situation flowcharts I played through what happens when, for example, medication is forgotten — from a quiet reminder to escalation to relatives.",
    learnings: ["Escalation levels are a design decision, not a technical one", "Flowcharts make ethical questions discussable", "Fewer data points, interpreted more clearly, beat more sensors", "Relatives are a user group of their own, with their own needs"],
    cover: { type: "image", src: "assets/repose-wristband.png", fit: "contain", bg: "paper" },
    gallery: [
      { type: "image", src: "assets/repose-wristband.png", fit: "contain", label: "Wristband features", span: "wide" },
      { type: "image", src: "assets/repose-flowchart.png", fit: "contain", label: "Situation flowchart", span: "wide" },
      { type: "video", src: "assets/repose-calendar.mp4", fit: "contain", label: "Reminders & calendar", span: "portrait" },
    ],
  },
  {
    id: "wasserziit",
    hidden: true,
    num: "04",
    name: "Wasserziit",
    accent: "var(--a-map)",
    glyph: "W",
    category: "Open Data · Data Integration · Information Design",
    year: "2025",
    role: "Concept · Design · Build",
    duration: "Personal project",
    team: "Solo",
    skills: ["Information Design", "Data Integration", "Frontend"],
    tags: ["Open Data", "Data Integration", "Information Design"],
    liveUrl: "https://nadiwe.github.io/badi-collector/",
    cta: "View live project",
    sub: "Wasserziit brings together live information on public swimming spots in Zurich: opening hours, water temperatures and how busy they are.",
    teaser: "Public data — made usable in everyday life.",
    contextTitle: "Starting point",
    context: "A personal project: Wasserziit brings together live information on more than 20 public swimming spots in Zurich — opening hours, water temperatures and occupancy, live and free.",
    context2: "It grew out of my interest in translating publicly available data into a digital product that works in everyday life.",
    challenge: "The data comes from different sources and interfaces, in varying quality and freshness.",
    challenge2: "The open question was how to present continuously updating information so that you can tell in seconds which spot suits you right now.",
    approach: "I built an information hierarchy for dynamic data: status and occupancy first, details on demand. Filters by pool type and a favourites function make options comparable.",
    approach2: "From fetching the data to the structure and the interface, I built everything myself — trying out new design and coding tools along the way.",
    learnings: ["Real, messy data tests design decisions harder than dummy content does", "Dynamic values need visible freshness and a fallback", "Filters and favourites replace a lot of explaining", "Building it yourself sharpens your sense of what is technically feasible"],
    cover: null,
    gallery: [],
  },
];
